//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhieuEVN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDiemThaoTac
    {
        public string MaDiaDiemThaoTac { get; set; }
        public string MaPhieuThaoTac { get; set; }
        public string MaDiaDiem { get; set; }
        public string Muc { get; set; }
        public Nullable<bool> HoanThanh { get; set; }
    }
}
