//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhieuEVN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDiem
    {
        public string MaDiaDiem { get; set; }
        public string TenDiaDiem { get; set; }
        public string DiaChi { get; set; }
    }
}
