//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhieuEVN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThaoTac
    {
        public string MaPhieuThaoTac { get; set; }
        public string TenPhieuThaoTac { get; set; }
        public string NguoiVietPhieu { get; set; }
        public string ChucVuVietPhieu { get; set; }
        public string NguoiDuyetPhieu { get; set; }
        public string ChucVuDuyetPhieu { get; set; }
        public string NguoiGiamSat { get; set; }
        public string ChucVuGiamSat { get; set; }
        public string NguoiThaoTac { get; set; }
        public string ChucVuThaoTac { get; set; }
        public string MucDichThaoTac { get; set; }
        public Nullable<System.DateTime> TgBatDau { get; set; }
        public Nullable<System.DateTime> TgKetThuc { get; set; }
        public string DonViDeNghi { get; set; }
        public string DieuKienThucHien { get; set; }
        public string LuuYKetDay { get; set; }
        public string BienPhapAnToan { get; set; }
        public string LuuYKhac { get; set; }
        public string SuKienBatThuong { get; set; }
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
        public Nullable<System.DateTime> NgayThaoTac { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
