//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhieuEVN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLPhieuDienLucEntities : DbContext
    {
        public QLPhieuDienLucEntities()
            : base("name=QLPhieuDienLucEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiaDiem> DiaDiems { get; set; }
        public virtual DbSet<DiaDiemThaoTac> DiaDiemThaoTacs { get; set; }
        public virtual DbSet<GiaoNhanSau> GiaoNhanSaus { get; set; }
        public virtual DbSet<GiaoNhanTruoc> GiaoNhanTruocs { get; set; }
        public virtual DbSet<PhieuThaoTac> PhieuThaoTacs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TrinhTuThaoTac> TrinhTuThaoTacs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
