//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhieuEVN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrinhTuThaoTac
    {
        public int MaTrinhTuThaoTac { get; set; }
        public string MaDiaDiemThaoTac { get; set; }
        public string Buoc { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> DaThucHien { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public string NguoiRaLenh { get; set; }
        public string NguoiNhanLenh { get; set; }
    }
}
